### ISSUE TITLE
Code for recommendation engine 

### ISSUE THREAD

**Issue by worldmovers** [Recolize/recolize-recommendations-magento2#14]
Hi, 
I was trying to use a python based recommendation engine code in your plugin. Can you please help how can we modify/see the existing recommendation engine source code and how do we implement our custom code. 
Thanks

**Comment by ma4nn** [comment]
Hi @worldmovers,

thanks for your issue request.

This repository contains the [Magento 2](https://magento.com/) Extension specific to the [Recolize Recommendation Engine](https://www.recolize.com).

It is per se not intended to be used with any other recommendation engine, but of course you can use it as a starting point for your implementation as it is licensed under the [GPLv3](https://github.com/Recolize/recommendation-engine-magento2/blob/master/LICENSE.txt).

Best regards,
Christoph
