### ISSUE TITLE
PHP Deprecated, str_replace() on PHP 8.1.25

### ISSUE THREAD

**Issue by Flow09AT** [Recolize/recolize-recommendations-magento2#16]
Hi,
on running the "recolize_recommendation_engine_cronjob" conjob we got this "PHP Deprecated" message flooding our cron logs.  

`PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /vendor/recolize/module-recommendation-engine-magento2/Model/Feed/ProductToColumnMapper.php on line 62`

Running Magento 2.4.6-p2 on PHP 8.1.25 using recolize/module-recommendation-engine-magento2 V1.1.2

**Comment by ma4nn** [comment]
Hi @Flow09AT,

thanks for your report. 

Unfortunately I was not able yet to reproduce it, seems like it is dependent on your product attributes somehow as the mentioned code part does not contain a `str_replace()` call:
https://github.com/Recolize/recolize-recommendations-magento2/blob/0f7d0d83ce4b53b3149661c7d2009cb703a270ed/Model/Feed/ProductToColumnMapper.php#L62

Can you try to exclude the attributes via the config setting `recolize_recommendation_engine/product_feed/attributes_to_exclude` or to output the `$attribute` in this code part?

As an alternative of course you can also open a support request if you send us an email and we can have a look at your system.

**Comment by Flow09AT** [comment]
@ma4nn thanks for the reply, the issue can be closed. Found the reason of the problem in a custom plugin which i didn't noticed initial.
